spring:
  application:
    name: helpdesk
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
spring-doc:
    paths-to-match:
      - /api/v1/**
      - /autenticacao/**
    swagger-ui:
      use-root-path: true
file:
  upload-dir: /home/lucas/uploadDir
jwt:
  secret: Jg0K9vXqY7h2NfR8WzqP3LmE4aUcTbVsX9EyQpBrKdHgZcMwFl
  expiration: 86400000 # 1 dia em milissegundos


